### ISSUE TITLE
05242018_Table Edits

### ISSUE THREAD

**Issue by SArabUCD** [UCCC/McLeod#1]
Please make the following changes in the existing report:

- [x] Table 1B Cumulative demographic differences: Please add unit to Age, Height, Weight text for quick interpretation.
- [ ]  Table 1D: Please add explanation to decreased cohort size (109 -> 106) due to invalid (**/**/1900) recorded discharge date.
- [x] Please add sum to table 2A to denote total patient count in cohort
- [ ] For Table 3A please add additional text to explanatory section: "Each row is a unique provider." (And clarify, how we defined provider from the raw data.
- [x] Figures 4A Basic Rx Information: Please add jitter() ggplot function
- [ ] Oxycodone: please exclude patients highest RX_Supply_days of n>100 and provide count for those patients. 
- [x] For all plots, please include x-axis label, y-axis label and descriptive title
- [ ] Please provide table for each plot including mean, median, range, IQ range (like before)

**Comment by vtmacox** [comment]
We need to talk about the four unchecked boxed because these require a little more explanation.  Additionally, in the future, will you separate all the asks into individual issues?  I need to be able to address individual issues and close them as they are addressed.

**Comment by SArabUCD** [comment]
Sounds good. These four unchecked boxes are all things you have done in prior conversations. Please send me an invite for a time you are free on Tuesday 5/29. Thanks!
