### ISSUE TITLE
Review Tables/Figures 4 (Boxplots)

### ISSUE THREAD

**Issue by SArabUCD** [UCCC/McLeod#10]
Review these in more detail with Lisa.

**Comment by SArabUCD** [comment]
- [ ] Combine "Hydrocodone/Acetaminophen" and "Hydrocodone/APAP 5/500". For all intensive purposes these are the same medications.

- [ ] Combine "Meperidine HCL" and "Meperidine HCL/PF"

- [ ] Combine "Methadone HCL" and "Methadone HCL Oral Syringe"

- [ ] Combine "Morphine Sulfate", "Morphine Sulfate PF" , "Morphine Sulfate SR" and "Morphine Sulfate/PF"

- [ ] Combine "Oxycodone HCL", "Oxycodone HCL/Acetaminophen", "Oxycodone SA", and "Oxycodone/APAP 5/325"

**Comment by vtmacox** [comment]
This is going to take time to do correctly.  I'll work on this.

**Comment by vtmacox** [comment]
Done
