### ISSUE TITLE
Remove From Analysis

### ISSUE THREAD

**Issue by SArabUCD** [UCCC/McLeod#13]
After speaking with Lisa about the medications, we can remove a whole bunch that are IV only:

- [x] Hydromorphone HCL in 0.9% NACL

- [x] Hydromorphone HCL Vial/Syringe

- [x]  Hydromorphone Infusion (Neo/Ped) for non-standard Conc/Vol

- [x] Hydromorphone PCA 0.2 Mg/ML

- [x] Hydromorphone PCA 10mg/50ml-ns

- [x] Hydromorphone PCA 200mcg/ml-ns

- [x] Hydromorphone PCA 6mg/30ml-ns

- [x] Morphine 1mg/ml in D5W 50 ML IV Infusion Syringe (Neo/Ped)

- [x] Morphine 100mg/100ml-D5W

- [x] Morphine PCA 1mg/ml

**Comment by vtmacox** [comment]
Can you send me the new list of medications you want to use in a .csv file?  I am keeping separate tables with these values for reproducibility sake.

**Comment by SArabUCD** [comment]
Hi Matt, sure. What do you want me to do with the medications that are being combined?

**Comment by vtmacox** [comment]
You can leave them in their own individual rows and I will adjust them in the code.

**Comment by SArabUCD** [comment]
Great. Github doesn't support CSV so I will email.
