### ISSUE TITLE
Provider specialty Figure 4D

### ISSUE THREAD

**Issue by vtmacox** [UCCC/McLeod#14]
In the what I've labelled Figure 4D, I've plotted the RX_DAYS_SUPPLY by provider and medication.  These plots only seemed to have a single data point per box-plot.  Taking a closer look at this, it looks like there are only one point per RX_DAYS_SUPPLY per specialty per medication.  The way the data are aggregated there are multiple counts per same day, but not different days.  For example if there are three instances provider specialty is EME, medication is Hypdromorphone HCL, and RX_DAYS_SUPPLY is 10.  These are all aggregated by specialty, medication and RX_DAYS_SUPPLY, so this only counts as 1 data point.  If I "spread" this out.  The plots wouldn't be any different, there would just be more points with the same values.  

Let me know if you need more explanation.

**Comment by SArabUCD** [comment]
A little more explanation would be good - can you a) describe the table that the max Rx_days_supply, medication, and provider criteria generate, and then b) I'm not sure I understand why the "day" matters?

**Comment by SArabUCD** [comment]
Add table 4D in sorted by medication type; rename variables and cut the actual boxplots.

**Comment by vtmacox** [comment]
Done
