### ISSUE TITLE
CHCO Table 4D

### ISSUE THREAD

**Issue by SArabUCD** [UCCC/McLeod#20]
For table 4d (CHCO) can we include the kids who had over 100 RX_Days_Supplys of Oxy (n = 20) (from tables 4A section.)

**Comment by vtmacox** [comment]
Are you saying that you want different criteria for different reports?  In other words, you don't want over 100 RX_DAYS_SUPPLY for DH but you do for CHCO.

**Comment by SArabUCD** [comment]
In that table for 4d, for both CHCO and DH it would be great to just have those kids included - but just in that table, not the graphs. Would that work?

**Comment by vtmacox** [comment]
Table 4d no otuputs data for all RX_DAYS_SUPPLY.  Even for values over 100.
