### ISSUE TITLE
Denver Health Response

### ISSUE THREAD

**Issue by SArabUCD** [UCCC/McLeod#24]
Hi Matt,
Here's the response from DH:

The R program ran.  Two things I’d like to run by you before sending the output file:
 
First, I think I may have asked this with one of the QA reports.  Regardless, when I select the hospital, database server name and database name, selecting the database name “VDW” works, whereas selecting the database name “VDW.aligned” does not (I get an error that the login failed).  When I write SQL queries, I have to specify VDW.aligned as the data source, in part, because there are CDM views and other views that are similarly named, including views that have the same exact names as VDW ‘tables’ (e.g. PRESCRIBING is the name of a table in both VDW and CDM and has corresponding views in our environment).  So, this is a long way of saying that while the package ran, I’m not 100% sure it ran against the correct views.  Is there a way to double check this?  Does the fact that the package ran mean that it ran against the ‘correct’ views?

Second, I got a bunch of warnings that may or may not be a problem (e.g. “Removed 84 rows containing non-finite values (stat_boxplot)”)

Please advise! 

Thanks,
Sophia

**Comment by vtmacox** [comment]
The first issue is an IT problem that I can't control.  I do not control permissions or access to the VDW.  If there are login issues, they need to talk with either their IT people or the CHORDS IT people.  

For the second issue, as long as the package produces a word document, there shouldn't be any problems.  The errors are just likely a byproduct how missing values when manipulating data and shouldn't cause any problems.

**Comment by vtmacox** [comment]
I'm not sure I fully understand the issue.  Is the problem that there views in one database (e.g., VDW) that have the same names as tables in another database (e.g., VDW.aligned)?  In any case, I don't have permissions to either of these databases so there isn't a check I can do.  I think the easiest solution is to figure out the login issue and ensure the package runs on the correct database--mainly because I can't access their database to do any checks.

**Comment by zuckerr** [comment]
Right, VDW and VDW.aligned have an identical table structure but VDW. aligned contains a more complete set of data. We want to run this against VDW.aligned but it sounds like they are having this log in issue Ken mentioned. I'll let them know that it's something they'll need to resolve on their end.
