### ISSUE TITLE
Error in tools::file_path_as_absolute(input)

### ISSUE THREAD

**Issue by accomer** [UCCC/McLeod#25]
I've gone through the steps to run this report and I'm running into the following error:

Error in tools::file_path_as_absolute(input) : file '' does not exist
In addition: Warning message:
In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="": The filename, directory name, or volume label syntax is incorrect

Have I missed something?

**Comment by vtmacox** [comment]
This is the same error you are running into with the other package.  Again, I think this is a system issue.  Try the solution form UCCC/QA#18
