### ISSUE TITLE
DH Report Only Has 2 Years of Data

### ISSUE THREAD

**Issue by SArabUCD** [UCCC/McLeod#26]
The report we received back only contains two years of data (2016, 2017). We requested data from 2011 - 2017. Please let me know how we should proceed.

**Comment by SArabUCD** [comment]
Hmm. Could it be related to the issue we were having before with the dataset versions?

**Comment by vtmacox** [comment]
My understanding was that the test set I was working with from DH, is very similar to the actual data.  I think Rachel should be able to get to the bottom of this.

**Comment by zuckerr** [comment]
I'm assuming this is related to the permission error Ken was experiencing earlier. Let me write him a note.

**Comment by zuckerr** [comment]
@vtmacox 
Request from Ken:
1.	Please ask Matt to include the following options in the R package dropdowns:
o	Server name: uat.edwsql.hosp.dhha.org 
o	Database: VDW_Aligned
2.	If possible, please ask  delete the older options, which for DH I believe include vwphbisql06, vwedwtstsql04, VDW.aligned and VDW.dbo

**Comment by zuckerr** [comment]
This resolved the issue.
