### ISSUE TITLE
Potential Error in Table 4D DH

### ISSUE THREAD

**Issue by SArabUCD** [UCCC/McLeod#27]
In table 4D (the prescription supply days by medication and provider specialty) in the Denver Health output, I am worried about the frequency counts. I think I was under the impression that we were still taking the single highest RX_Days_Supply per patient per medication, in which case the frequency for each prescription ought (I thought) to add up to our total patient count (109). 

For the oxycodone in particular, however, the total frequencies add up to ~829, so clearly we are capturing more than one prescription per patient. 

How should we proceed?

**Comment by vtmacox** [comment]
I don't know why this is, but that part of the code was commented out so it returns all values.  I vaguely recall and ask for all of the values to be returned in one of our more recent back and forths (but haven't gone through emails to confirm this).  I can uncomment that code to return the max values.  For clarity, it is the max per procedure type, specialty, and medication, not by patient.  

If you don't want to have people rerun the package, you can just delete the unnecessary rows.

**Comment by SArabUCD** [comment]
Thanks for clarifying. 

I know we had a lot of back and forth on this, but I can't recall why we settled on commenting out the code - there very well could have been a good reason for it... I can search my emails too.

I'm wondering though, if we can maybe also ask a different question which is: do specialties have different discharge prescribing practices for different medications? 

So ideally we would want: procedure type (spine/pectus),  specialty, medication (where medication we would try to get to "discharge" by assuming the highest value for each patient for each medication, and frequency. Can you recall why we may have changed our approach?

**Comment by vtmacox** [comment]
Regarding the question you want to answer, maybe this is why we decided to change the code.  You would need to have every value of supply days in order to answer that question.  The reason for that is, if you have someone who prescribed 283 days of Oxy, but this only happend once, this won't tell you anything about that specialty because this only happend once.   Looking at the distribution and comparing between specialties will let you answer that question.

**Comment by vtmacox** [comment]
I will go through and get the max number of supply days per medication per patient, then reproduce the table using that data and send it to you.

**Comment by vtmacox** [comment]
Change has been made with commit 96bd8f6372470885230db4f22521f849390f3302
